version: "3.8"
services:
  aniwatch-api:
    image: ghcr.io/ghoshritesh12/aniwatch:v2.17.0
    container_name: aniwatch-api
    ports:
      - "4000:4000"
    restart: unless-stopped
    depends_on:
      - redis
    environment:
      - ANIWATCH_API_REDIS_CONN_URL=redis://localhost:6379

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    environment:
      - REDIS_APPENDONLY=yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  redis_data:
    driver: local